name: sqnm
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.7.1
  - libcxx=14.0.6
  - libffi=3.4.4
  - libmpdec=4.0.0
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.1
  - python=3.13.2
  - python_abi=3.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - black==25.1.0
      - click==8.2.0
      - contourpy==1.3.2
      - cycler==0.12.1
      - filelock==3.18.0
      - fonttools==4.58.0
      - fsspec==2025.5.1
      - isort==6.0.1
      - jinja2==3.1.6
      - kiwisolver==1.4.8
      - markupsafe==3.0.2
      - matplotlib==3.10.3
      - mpmath==1.3.0
      - mypy==1.15.0
      - mypy-extensions==1.1.0
      - networkx==3.5
      - numpy==2.2.5
      - packaging==25.0
      - pandas==2.3.1
      - pathspec==0.12.1
      - pillow==11.2.1
      - platformdirs==4.3.8
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - six==1.17.0
      - sympy==1.14.0
      - torch==2.7.1
      - torchaudio==2.7.1
      - torchvision==0.22.1
      - typing-extensions==4.13.2
      - tzdata==2025.2
